### ISSUE TITLE
Moving album leads to broken pictures

### ISSUE THREAD

**Issue by CChiappa** [jradwan/Piwigo-physical_photo_move#11]
After moving an album, the first symptom was the lack of execute permissions:
$ ls -ld January2015
drw-r--r-- 1 www-data www-data 2.2K Jan  1  2016 January2015/
Potentially worth noting, previous to move, the file was owned by chris.www-data with 775 permissions.  Having fixed permissions, the album will load but all of the pictures simply show an exclamation point indicating an error.  There doesn't seem to be anything in the web server's error log.  The access log looks reasonably normal I think, ie:
1.2.3.4 - - [01/Feb/2018:20:19:50 -0500] "GET /piwigo/i/galleries/Chris/2015/January2015/20150102_113318_Noelie_Will_Julia-me.jpg?ajaxload=true HTTP/1.1" 200 595 "https://www.hostname.com/piwigo/picture/36953-20150102_113318_noelie_will_julia/category/January2015" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
None of the resizes of the picture work, however selecting the "Original" size does show the correct picture.  I'm not sure where I should be looking for debugging information, any hints?  Thanks for the work on this, it's a lifesaver!

**Comment by jradwan** [comment]
Man, that is odd. Sorry it's already causing problems for you (again)!

So was the directory physically moved to the new location (under /piwigo/galleries)? And what about the corresponding representative folder (under /piwigo/_data/i/galleries)?

If you have access to your database (i.e., via phpMyAdmin) can you check the images and categories tables? On the images table, the path column should reflect the new physical path under /piwigo/galleries) and on the categories table, the id_uppercat column should contain the category id of the new parent album.

As for the permissions, the plugin does set all the permissions to 644 (even in version 1.x). I think I got that from looking at another plugin that did file operations. But now I realize that in my situation, all of my images are on a NAS and my galleries folder is symlinked to a folder on the NAS so all permissions appear as 777 to Piwigo. Which means my testing hasn't been perfect when it comes to file system-level permissions. That being said, 644 should be sufficient but I guess it could make a difference depending on ownership of the files and the user your web server is running as. It looks like you're using www-data like I am, so I guess I have to test more around the permissions.

**Comment by CChiappa** [comment]
That was easy!  It was just the permissions of the representative folder, which was also missing +x.  Directories without execute permission behave strangely, ie
$ mkdir blah
$ cd blah
$ touch a b c
$ ls -l
total 0
-rw-r--r-- 1 chris users 0 Feb  3 06:59 a
-rw-r--r-- 1 chris users 0 Feb  3 06:59 b
-rw-r--r-- 1 chris users 0 Feb  3 06:59 c
$ chmod -x .
$ ls -l
ls: cannot open directory '.': Permission denied
$ cd ..
$ ls -l blah
ls: cannot access 'blah/a': Permission denied
ls: cannot access 'blah/c': Permission denied
ls: cannot access 'blah/b': Permission denied
total 0
-????????? ? ? ? ?            ? a
-????????? ? ? ? ?            ? b
-????????? ? ? ? ?            ? c
$ cd blah
-bash: cd: blah: Permission denied
$ 

Looking at include/functions.inc.php, I'm not sure how php implements rename() (and maybe you need to worry about Windows etc as well) but I'm pretty sure on UNIX-like operating systems, permissions are retained after a rename() operation.  If moving between filesystems, I would hope the equivalent functionality preserves permissions as well.  So, I would guess a lot of the chmod() calls are not necessary.  You might find that, particularly since physical albums appeal to people doing their own maintenance, that some people have ie group permisisons that get overridden by explicitly setting it.

**Comment by CChiappa** [comment]
This sledgehammer of a patch fixes the issue for me. I'm not a php programmer so feel free to disregard and do it right. :)
[functions_move_chmod.dif.txt](https://github.com/jradwan/Piwigo-physical_photo_move/files/1691758/functions_move_chmod.dif.txt)

**Comment by evadim** [comment]
I have same issue with move album - it fail with traceback because of incorrect permissions.
Direcrories without X flag not "behave strangely" as X for directory means "can list directory", so it have to be 755 not 644. 644 for file is correct, as executable file not good idea.

BTW: your plugin is what I miss wery much so thanks a lot!

**Comment by jradwan** [comment]
Ok, cool ... glad it was just the permissions! 

I'll take a look at your suggested patch.

**Comment by jradwan** [comment]
Thanks for the suggested patch! I'll be pushing out 2.01 shortly which includes this.
