### ISSUE TITLE
Album with subalbums but no pictures leads to error

### ISSUE THREAD

**Issue by CChiappa** [jradwan/Piwigo-physical_photo_move#12]
I had an album, Chris/Blah2015 which had a a bunch of subalbums, Chris/Blah2015/{22,23,24,25}Jun2015 .  However, there were no pictures at the Chris/Blah2015 level.  Going to the Move tab leads to an error:

Piwigo encountered an irrecoverable error

[get_image_infos] invalid image identifier 

#1	get_image_infos /av/piwigo/plugins/physical_photo_move/admin.php(132)
#2	include_once /av/piwigo/admin/plugin.php(68)
#3	include /av/piwigo/admin.php(311)

Adding an image temporarily to Chris/Blah2015 allows the move operation to work

**Comment by jradwan** [comment]
Looks like it's failing trying to get the thumbnail image for the album to display on the Move tab. So probably if there's not at least one image, there's no default thumbnail. I'll look into this ...

**Comment by jradwan** [comment]
Added a fix for this in 2.01.
