### ISSUE TITLE
Russian translation.

### ISSUE THREAD

**Issue by evadim** [jradwan/Piwigo-physical_photo_move#15]
New language: Russian. All words translated.
I'm 80% satisfied with result for now, because of very misleading words to describe difference between physical and virtual when we talk about files and filders.
[PPM_ru_RU_by_evadim.tar.gz](https://github.com/jradwan/Piwigo-physical_photo_move/files/1693368/PPM_ru_RU_by_evadim.tar.gz)

**Comment by jradwan** [comment]
Thanks for the contribution! I'll add this in the next release (2.02, probably being pushed out tonight).
