### ISSUE TITLE
Does not work with Piwigo 2.9.3 release

### ISSUE THREAD

**Issue by NerdDoc** [jradwan/Piwigo-physical_photo_move#20]
Hello! Something goes wrong! After installing from Piwigo 2.9.3. web plugin manager i did not find PPM tab in the property of image.
My host operating system is Gentoo, web server is apache 2.4 and php -7.0

**Comment by jradwan** [comment]
The plug-in definitely works with 2.9.3 (that's what I'm running on both my development site and my main site). Are you sure you're looking at a photo that is in a _physical_ album? The "Move" tab won't appear for photos that were uploaded and in a virtual album, only photos that are in physical albums that are part of an FTP+Sync.

**Comment by NerdDoc** [comment]
Sorry, you definitely right! I used web uploaded album! I got a question, is it hard to convert virtual album to physical implementation on hard disk with human readable file names!

**Comment by jradwan** [comment]
Ok, glad that's all it was.

I don't use virtual albums, so I'm not sure. But I would think you'd probably have to manually rename the files from the upload folder and then move them into the physical subfolders you want. Probably not an easy task depending on how many photos you're dealing with.
