### ISSUE TITLE
Fallback to English for unsupported languages?

### ISSUE THREAD

**Issue by Arnie97** [jradwan/Piwigo-physical_photo_move#22]
If the user preferred language has not been translated yet, this extension will show the internal i18n tags, like DEST_ALBUM_HELP_2, MSG_RENAME_3, etc. While the variables are well-named and somewhat understandable, falling back to English would be a better choice in my opinion.

Since I've not read the code, one possible workaround is creating symbolic links to `en_UK`. Any ideas for more decent solutions?

**Comment by jradwan** [comment]
This is more a feature/issue with Piwigo itself and how it handles translations, not necessarily my extension.
