### ISSUE TITLE
Menu items not appearing, destination albums not populated

### ISSUE THREAD

**Issue by StephenAdams-hamont** [jradwan/Piwigo-physical_photo_move#24]
Using v2.04 installed through plugins list internally.

The gallery edit menu does not show the move tab.

The drop down option for physical move appears in the batch manager options but the destination albums list is not populated.

Using Clear "Mail" Theme

Piwigo 11.3.0
Operating system: Linux
PHP: 5.6.40 (Show info) [2021-02-08 21:09:25]
MySQL: 5.7.33 [2021-02-08 16:09:25]
Graphics Library: ImageMagick 7.0.10-10

**Comment by jradwan** [comment]
Odd. It's working for me in both of my Piwigo galleries:

Piwigo 11.3.0
Operating system: Linux
PHP: 7.4.9 (Show info) [2021-02-08 17:28:13]
MySQL: 8.0.23-0ubuntu0.20.10.1 [2021-02-08 17:28:13]
Graphics Library: External ImageMagick 6.9.10-23

Maybe your older version of PHP? Any errors or warnings on screen or in your web server logs?

**Comment by StephenAdams-hamont** [comment]
I have to update another piece of software on my server before moving to a newer PHP, so I will get that update done and let you know if that solves it.

**Comment by StephenAdams-hamont** [comment]
It's been a while, but finally had the free time to address the php version issue.  After update I uninstalled and reinstalled the plugin.  I continue to only see Properties and Center of Interest tabs when visiting the edit photo menu.

Piwigo 11.4.0 Check for upgrade
Operating system: Linux
PHP: 7.4.16 (Show info) [2021-05-03 16:27:27]
MySQL: 5.7.34 [2021-05-03 12:27:27]
Graphics Library: External ImageMagick 6.9.10-68

**Comment by jradwan** [comment]
Very strange.

If you add another extension that adds a tab to Photo Properties, like rotateImage (https://piwigo.org/ext/extension_view.php?eid=578), does the extra tab appear (Rotate, in this example)?

![image](https://user-images.githubusercontent.com/11047158/116941771-5b05f900-ac3e-11eb-8b2d-56388a545db8.png)

You mentioned a theme originally as well. If you switch back to one of the default Piwigo themes, does it work?

**Comment by StephenAdams-hamont** [comment]
Hello again and thanks for your reply.

I installed rotateImage and the tab appears immediately.  The themes I've mentioned are the built in ones, I was just mentioning them in case it was relevant.  The rotate tab appears in both the Clear and Dark themes.

**Comment by jradwan** [comment]
Maybe I should have started with a basic question. The photo you're looking at (on the properties page) ... is it in a _physical_ album? The extension is only for photos in physical (not virtual) albums so the Move tab won't appear unless the photo meets that criteria.

The album structure _should_ still appear in the Batch Manager though, are you still having that issue after the PHP update?

**Comment by StephenAdams-hamont** [comment]
I've just checked and indeed, I did virtual folders 11 months ago when I initially uploaded all these photos. I am sorry to have wasted your time, I'm at the stage now where I want to better organize the 60k photos and I see I have a different task ahead of me.

**Comment by jradwan** [comment]
No worries! Glad we got it figured out. With virtual folders all of your photos physically reside under the uploads folder. Since the albums are all virtual, you can just "move" them with the existing move action in batch manager. The physical files stay put, it's just their virtual locations that get updated. If you're good with SQL, you could even do some of that via back-door scripting. Good luck!
