### ISSUE TITLE
Error when moving directories with non-ASCII characters, and when subdirectories exist

### ISSUE THREAD

**Issue by miblo69** [jradwan/Piwigo-physical_photo_move#33]
This great plugin works as expected. However, there are two annoying issues.

When the Move is almost completed , t tries to delete the the source directory as the last step. But there are two circumstances when the deletion fails:
1) If the directory contains non-ASCII characters (in my case the Swedish characters åäöÅÄÖ). The directory removed from all files, but the deletion of the directory itself fails.
2) The second case is when there is a subdirectory such as "pwg_representative". This subdirectory is created by the VideoJS Plugin, and contains thumbnails of Videos.

The plugin works fine in other cases, but it is annoying to have to manually delete the empty directories through the CLI.

Thanks for your efforts!

Cheers,
Mike

**Comment by jradwan** [comment]
1. I'll have to test this out. I'm using PHP's rmdir command so not sure why that wouldn't work with high ASCII stuff).

2. That's weird, I know I've moved folders with the pwg_representative sub-folder (I also use VideoJS). I'll look into this as well.

Any messages from the extension when these situations occur?

**Comment by jradwan** [comment]
@miblo69 

How are you getting these files and folders with special characters into Piwigo? When I tried creating some physical test folders and files, my sync failed because Piwigo is not allowing special characters to begin with:

![image](https://github.com/jradwan/Piwigo-physical_photo_move/assets/11047158/77bafdd9-8920-4030-8e1c-ce33e91d4d8f)

**Comment by jradwan** [comment]
@miblo69 

I'm not able to replicate this. I created test folders and files with "special" characters (specifically the ones you listed) and the extension worked as expected: the files and folders were moved, nothing left behind. Same with the pwg_representative folder issue you indicated.

So I'm not sure what is causing your problem.

**Comment by jradwan** [comment]
Glad to hear it's resolved, and you're welcome. 😄
