### ISSUE TITLE
Move entire album?

### ISSUE THREAD

**Issue by jradwan** [jradwan/Piwigo-physical_photo_move#4]
Add option to move an entire physical album to a new location (i.e., move folder instead of individual file(s)).

**Comment by CChiappa** [comment]
This is the plugin I have been procrastinating on writing since I switched from G3 to Piwigo as well!  I had a somewhat different idea (I was going to capture md5sums and try to recognize physical moves during a sync) but this seems much better.

**Comment by jradwan** [comment]
@CChiappa it was something that had bothered me as well ever since switching from G3. It seemed no one else was going to write it so I decided to give it a shot! 😄 Feel free to fork and enhance ... I'm certainly open to suggestions!

**Comment by bigs38** [comment]
Hi,
I prefer to use physical album too, and I'm waiting for this option for many years now.
Do you think that it's possible to keep album ID in this case ?

**Comment by jradwan** [comment]
If/when I get around to moving an entire album, yes, I would think the album ID would remain the same, just the physical location would change.

**Comment by jradwan** [comment]
I've started working on this ([move-folder](https://github.com/jradwan/Piwigo-physical_photo_move/tree/move-folder) branch).

**Comment by jradwan** [comment]
Closed by PR #9.
